[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/auth/*"
  to = "/.netlify/functions/api/auth/:splat"
  status = 200

[[redirects]]
  from = "/docs/*"
  to = "/.netlify/functions/api/docs/:splat"
  status = 200

[[redirects]]
  from = "/sign/*"
  to = "/.netlify/functions/api/sign/:splat"
  status = 200

[[redirects]]
  from = "/"
  to = "/.netlify/functions/api"
  status = 200
